[build]
  command = "dotnet publish -c Release"
  publish = "bin/Release/net8.0/publish/wwwroot"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[build.environment]
  NETLIFY_USE_TOML = "true"
  ASPNETCORE_ENVIRONMENT = "Production"